language: node_js
node_js:
  - 14.5
cache:
  directories:
    - node_modules
script:
  - export REACT_APP_VERSION=$TRAVIS_BUILD_NUMBER
  - npm i
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: kkumar-folio.surge.sh 
  project: ./build/
on:
  branch: master