name: Deploy Surge Website   
on: [push]

jobs:
       build:                           
           runs-on: ubuntu-latest 
           name: Deploying to surge 
           steps:    
           - uses: actions/checkout@v2 
           - name: Install Node.js
             uses: actions/setup-node@v2-beta
             with: 
               node-version: 14.15 
               
           - name: install dependencies                              
             run: npm install
           - name: Update Build number
             env:
               RUN_NUMBER: ${{ github.run_number }}
             run: echo "REACT_APP_VERSION = $(($RUN_NUMBER + 50))" >> .env
             
           - name: .env file
             run: cat .env
             
           - name: Build App
             run: npm run build
             
           - name: Install Surge
             run: npm install --global surge
             
           - name: Run surge
             run: surge ./build kkumar-folio.surge.sh --token ${{ secrets.SURGE_TOKEN }}
